apiVersion: v1
kind: Service
metadata:
  labels:
    name: tidb-peer
  name: tidb-peer
  namespace: endgame 
spec:
  clusterIP: None
  ports:
  - name: status
    port: 10080
    protocol: TCP
    targetPort: 10080
  selector:
    name: tidb
  sessionAffinity: None
  type: ClusterIP
