apiVersion: v1
kind: Service
metadata:
  labels:
    name: tidb
  name: tidb
  namespace: endgame 
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql-client
    nodePort: 31279
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: status
    nodePort: 30842
    port: 10080
    protocol: TCP
    targetPort: 10080
  selector:
    name: tidb
  sessionAffinity: None
  type: NodePort
