apiVersion: v1
kind: Service
metadata:
  labels:
    name: tikv
  name: tikv-peer
  namespace: test4
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 20160
    protocol: TCP
    targetPort: 20160
  selector:
    name: tikv
  sessionAffinity: None
  type: ClusterIP
