apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.pd.name }} 
  name: {{ .Values.pd.name }} 
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    name: {{ .Values.pd.name }} 
  sessionAffinity: None
  type: ClusterIP
