apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: {{ .Values.tikv.name }}
  name: {{ .Values.tikv.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: {{ .Values.tikv.name }} 
  serviceName: {{ .Values.tikv.name }}-peer 
  template:
    metadata:
      labels:
        name: {{ .Values.tikv.name }}
    spec:
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: timezone
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          HOSTNAME=$(hostname)
          /tikv-server --addr=0.0.0.0:20160 \
              --advertise-addr=${HOSTNAME}.${HEADLESS_SERVICE_NAME}:20160 \
              --data-dir=/var/lib/tikv \
              --pd=${PD_SERVICE_NAME}:2379
        env:
        - name: HEADLESS_SERVICE_NAME
          value: {{ .Values.tikv.name }}-peer
        - name: PD_SERVICE_NAME
          value: {{ .Values.pd.name }}.{{ .Values.namespace }}
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
          readOnly: true
        image: {{ .Values.tikv.image | default "pingcap/tikv:v2.1.0" }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.tikv.name }}
        ports:
        - containerPort: 20160
          name: server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/tikv
          name: {{ .Values.tikv.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: {{ .Values.tikv.name }}
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
    status:
      phase: Pending

