apiVersion: v1
kind: Service
metadata:
  labels:
    name: pd-peer
  name: pd-peer
  namespace: endgame 
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: 2380
  - name: client 
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    name: pd 
  sessionAffinity: None
  type: ClusterIP
