apiVersion: v1
kind: Service
metadata:
  name: pd
  labels:
    name: pd 
  namespace: endgame
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    name: pd 
  sessionAffinity: None
  type: ClusterIP
