apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tikv
  labels:
    name: tikv
  namespace: endgame
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: tikv
  serviceName: tikv-peer
  template:
    metadata:
      labels:
        name: tikv
    spec:
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: timezone
      containers:
      - command:
        - /bin/sh
        - -ec
        - |
          HOSTNAME=$(hostname)
          echo $HOSTNAME
          /tikv-server --addr=0.0.0.0:20160 \
              --advertise-addr=${HOSTNAME}.${HEADLESS_SERVICE_NAME}:20160 \
              --data-dir=/var/lib/tikv \
              --pd=${PD_SERVICE_NAME}:2379
        env:
        - name: HEADLESS_SERVICE_NAME
          value: tikv-peer
        - name: PD_SERVICE_NAME
          value: pd.endgame 
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
          readOnly: true
        name: tidb
        image: pingcap/tikv:v2.1.0
        imagePullPolicy: IfNotPresent
        name: tikv
        ports:
        - containerPort: 20160
          name: server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/tikv
          name: tikv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: tikv
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
    status:
      phase: Pending

