apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base  
patches:
- pd-statefulset.yaml
- tidb-deployment.yaml
- tidb-init-job.yaml
- tikv-statefulset.yaml
namePrefix: dev-
