apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pd
  namespace: endgame 
spec:
  serviceName: dev-pd-peer
  template:
    spec:
      containers:
      - name: pd
        env:
        - name: PEER_SERVICE_NAME
          value: dev-pd-peer
        - name: SERVICE_NAME
          value: dev-pd
        - name: SET_NAME
          value: dev-pd
